### ISSUE TITLE
missing license in this repo

### ISSUE THREAD

**Issue by octanejohn** [Jenova-Framework/Jenova-Runtime#5]
missing the mit license in this repo, it should be included based on this statement

https://github.com/Jenova-Framework/J.E.N.O.V.A/discussions/2

https://github.com/Jenova-Framework/J.E.N.O.V.A?tab=readme-ov-file#-source-code

**Comment by TheAenema** [comment]
Hi, It's included in ReadMe
![image](https://github.com/user-attachments/assets/0d03b9e3-5356-4e7d-ade5-b08804b1e6ae)

**Comment by octanejohn** [comment]
its invalid, the same way the other license is on the other repo, it should be in this one too with license.txt and but with the mit license in it

**Comment by TheAenema** [comment]
I don't believe this is necessary since I've seen many projects include the license inside the README. However, I'll add it in the next merge just in case.
